### PR TITLE
Update to Julia 1.0

### PR DESCRIPTION
**Pull request by loleg**
Addresses #25 through a number of code changes. All tests passing without dependency warnings in the 0.7 and 1.0 releases. Additionally, functionality has been added to save schema and table data to file.

### CODE REVIEW

**Comment by loleg** [comment]
@roll please tag this release v0.1

**Comment by roll** [comment]
@loleg 
Thanks. Done

**Comment by scls19fr** [comment]
Tag should follow [semver](https://semver.org/) ie v0.1.0

**Comment by scls19fr** [comment]
It's better to install [attobot](https://github.com/attobot/attobot) previously before tagging so it will automatically create a PR
at https://github.com/JuliaLang/METADATA.jl/pulls

**Pull request merged**
